name: CI/CD

on:
  push:
    branches:
      - dev
      - prod

env:
  PYTHON_VERSION: "3.11"
  IMAGE_NAME: onnx-mlops-api

  # Una sola Container App para ambos
  AZURE_CONTAINERAPP_NAME_DEV: "mnist-api-dev"
  AZURE_CONTAINERAPP_NAME_PROD: "mnist-api-dev"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_CONTAINER_NAME: "proyecto-ml"
      MODEL_BLOB_PATH: "models/mnist-12.onnx"
      TEST_INPUT_BLOB_PATH: "data/test_data_set_0/input_0.pb"
      TEST_OUTPUT_BLOB_PATH: "data/test_data_set_0/output_0.pb"
      MAX_TEST_OUTPUT_DIFF: "0.001"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

  build_push_and_rollout_dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare az (containerapp extension)
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add --name containerapp --upgrade

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push images to ACR (dev)
        run: |
          set -euo pipefail
          ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}
          TAG_FLOATING=dev
          TAG_IMMUTABLE=dev-${{ github.sha }}

          docker build -t $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE .
          docker push $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE

          docker tag  $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_FLOATING
          docker push $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_FLOATING

      - name: Rollout new revision (dev) - revision copy
        run: |
          set -euo pipefail
          ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}
          RG=${{ secrets.AZURE_RESOURCE_GROUP }}
          APP="${{ env.AZURE_CONTAINERAPP_NAME_DEV }}"
          TAG_IMMUTABLE=dev-${{ github.sha }}

          az containerapp revision copy \
            --name "$APP" \
            --resource-group "$RG" \
            --image "$ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE" \
            --set-env-vars ENVIRONMENT=dev APP_VERSION=${{ github.sha }}

  build_push_and_rollout_prod:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare az (containerapp extension)
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add --name containerapp --upgrade

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push images to ACR (prod)
        run: |
          set -euo pipefail
          ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}
          TAG_FLOATING=prod
          TAG_IMMUTABLE=prod-${{ github.sha }}

          docker build -t $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE .
          docker push $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE

          docker tag  $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_FLOATING
          docker push $ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_FLOATING

      - name: Rollout new revision (prod) - revision copy
        run: |
          set -euo pipefail
          ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}
          RG=${{ secrets.AZURE_RESOURCE_GROUP }}
          APP="${{ env.AZURE_CONTAINERAPP_NAME_PROD }}"
          TAG_IMMUTABLE=prod-${{ github.sha }}

          az containerapp revision copy \
            --name "$APP" \
            --resource-group "$RG" \
            --image "$ACR_NAME.azurecr.io/${{ env.IMAGE_NAME }}:$TAG_IMMUTABLE" \
            --set-env-vars ENVIRONMENT=prod APP_VERSION=${{ github.sha }}
